#!/bin/bash
# Copyright (c) 2013 The CoreOS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# LICENSE file referenced above has been appended from
#
#   https://github.com/coreos/init
#   https://raw.githubusercontent.com/coreos/init/master/LICENSE
#
# Copyright (c) 2013 The CoreOS Authors. All rights reserved.
# Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
# 
#    * Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above
# copyright notice, this list of conditions and the following disclaimer
# in the documentation and/or other materials provided with the
# distribution.
#    * Neither the name of Google Inc. nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -e -o pipefail

if [[ -z "${USER}" || "${USER}" == root ]]; then
    UPDATE_USER="core"
else
    UPDATE_USER="${USER}"
fi

USAGE="Usage: $0 [-l] [-u user] [-a name file1... | -d name]
Options:
    -u USER     Update the given user's authorized_keys file [${UPDATE_USER}]
    -a NAME     Add the given keys, using the given name to identify them.
    -A NAME     Add the given keys, even if it was disabled with '-D'
    -n          When adding, don't replace an existing key with the given name.
    -d NAME     Delete keys identified by the given name.
    -D NAME     Disable the given set from being added with '-a'
    -l          List the names and number of keys currently installed.
    -h          This ;-)

This tool provides a consistent way for different systems to add ssh public
keys to a given user account, usually the default '${UPDATE_USER}' user.
If -a, -A, -d, nor -D are provided then the authorized_keys file is simply
regenerated using the existing keys.

With the -a option keys may be provided as files on the command line. If no
files are provided with the -a option the keys will be read from stdin.
"

ADD_NAME=""
DEL_NAME=""
REPLACE=1
ENABLE=0
DISABLE=0
LIST_ALL=0

while getopts "lnu:a:A:d:D:h" OPTION
do
    case $OPTION in
        l) LIST_ALL=1 ;;
        n) REPLACE=0 ;;
        u) UPDATE_USER="$OPTARG" ;;
        a) ADD_NAME="$OPTARG"; ENABLE=0 ;;
        A) ADD_NAME="$OPTARG"; ENABLE=1 ;;
        d) DEL_NAME="$OPTARG"; DISABLE=0 ;;
        D) DEL_NAME="$OPTARG"; DISABLE=1 ;;
        h) echo "$USAGE"; exit;;
        *) exit 1;;
    esac
done

shift $(( OPTIND - 1 ))

UPDATE_GROUP=$(id -ng "${UPDATE_USER}")
UPDATE_HOME=$(getent passwd "${UPDATE_USER}" | cut -d: -f6)
if [[ -z "${UPDATE_HOME}" ]]; then
    echo "$0: ${UPDATE_USER}: unknown home directory" >&2
    exit 1
elif [[ ! -d "${UPDATE_HOME}" ]]; then
    echo "$0: ${UPDATE_HOME}: home directory is not a directory"
    exit 1
fi

# Check for an alternate path for testing
SSH_DIR="${_TEST_SSH_PATH:-${UPDATE_HOME}/.ssh}"

# Everything we do should be user-access only!
umask 077

# If this is the first time this script has run we don't want to wipe out
# any existing keys, someone might not like unexpectedly losing access.
KEYS_DIR="${SSH_DIR}/authorized_keys.d"
if [[ ! -d "${KEYS_DIR}" ]]; then
    mkdir -p "${KEYS_DIR}"
    if [[ -f "${SSH_DIR}/authorized_keys" ]]; then
        cp -a "${SSH_DIR}/authorized_keys" \
            "${KEYS_DIR}/old_authorized_keys"
    fi
fi

# Make sure .ssh is sane
chown "${UPDATE_USER}:${UPDATE_GROUP}" "${SSH_DIR}" "${KEYS_DIR}"

if [[ -n "$ADD_NAME" ]]; then
    ADD_PATH="${KEYS_DIR}/${ADD_NAME}"
    if [[ ${ENABLE} -eq 0 && -f "${ADD_PATH}" && ! -s "${ADD_PATH}" ]]; then
        # -a will not replace a zero length file, -A will
        echo "Skipping add ${ADD_NAME} for ${UPDATE_USER}, disabled."
    elif [[ ${REPLACE} -eq 0 && -f "${ADD_PATH}" ]]; then
        # -n with -a or -A will not replace an existing file of any size
        echo "Skipping add ${ADD_NAME} for ${UPDATE_USER}, already exists."
    else
        keyfile=$(mktemp "${ADD_PATH}.XXXXXXXXXX")
        trap "rm -f '${keyfile}'" EXIT
        chown "${UPDATE_USER}:${UPDATE_GROUP}" "${keyfile}"
        cat "$@" > "${keyfile}"
        echo "Adding/updating $ADD_NAME:"
        ssh-keygen -l -f "${keyfile}"
        mv "${keyfile}" "${ADD_PATH}"
        trap - EXIT
    fi
fi
if [[ -n "$DEL_NAME" ]]; then
    if [[ "${DISABLE}" -eq 0 ]]; then
        if [[ ! -f "${KEYS_DIR}/${DEL_NAME}" ]]; then
            echo "$0: no key set named ${DEL_NAME} found for ${UPDATE_USER}" >&2
            exit 1
        else
            echo "Removing ${DEL_NAME}:"
            ssh-keygen -l -f "${KEYS_DIR}/${DEL_NAME}" || true
            rm "${KEYS_DIR}/${DEL_NAME}"
        fi
    else
        echo "Disabling ${DEL_NAME}:"
        ssh-keygen -l -f "${KEYS_DIR}/${DEL_NAME}" || true
        truncate --size=0 "${KEYS_DIR}/${DEL_NAME}"
    fi
fi

if [[ "$(find "${KEYS_DIR}" -type f -size +1c)" ]]; then
    if [[ ${LIST_ALL} -eq 1 ]]; then
        echo "All keys for ${UPDATE_USER}:"
        for keyfile in "${KEYS_DIR}/"*; do
            echo "${keyfile##*/}:"
            ssh-keygen -l -f "${keyfile}"
        done
    fi
    allkeys=$(mktemp "${SSH_DIR}/authorized_keys.XXXXXXXXXX")
    trap "rm -f '${allkeys}'" EXIT
    chown "${UPDATE_USER}:${UPDATE_GROUP}" "${allkeys}"
    echo "# auto-generated by $0" > "${allkeys}"
    cat "${KEYS_DIR}/"* >> "${allkeys}"
    mv "${allkeys}" "${SSH_DIR}/authorized_keys"
    echo "Updated ${SSH_DIR}/authorized_keys"
else
    # The user may delete the last key authorized_keys.d but we won't touch
    # authorized_keys after that, they are on their own at that point.
    echo "$0: no keys found in ${KEYS_DIR}" >&2
    exit 1
fi
